spring:
  cloud:
    discovery:
        locator:
          enabled: false
          lower-case-service-id: true 
    gateway:
      routes:
        - id: movie-service
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
        - id: series-service
          uri: lb://series-service
          predicates:
            - Path=/series/**
server:
  port: ${SERVER_PORT:8080}
  
eureka:
  instance:
    hostname: eureka-server
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: servicio gateway
  svc:
    intanceid: ${eureka.instance.instance-id}
    port: ${server.port}
