server:
   port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://db-mongo:27017/backend
  rabbitmq:
    username: guest
    password: guest
    host: rabbit-mq
    port: 5672 
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

queue:
  serie:
    name: SerieQueue
